/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateModulArgs } from "./CreateModulArgs";
import { UpdateModulArgs } from "./UpdateModulArgs";
import { DeleteModulArgs } from "./DeleteModulArgs";
import { ModulFindManyArgs } from "./ModulFindManyArgs";
import { ModulFindUniqueArgs } from "./ModulFindUniqueArgs";
import { Modul } from "./Modul";
import { ModulService } from "../modul.service";

@graphql.Resolver(() => Modul)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ModulResolverBase {
  constructor(
    protected readonly service: ModulService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Modul",
    action: "read",
    possession: "any",
  })
  async _modulsMeta(
    @graphql.Args() args: ModulFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Modul])
  @nestAccessControl.UseRoles({
    resource: "Modul",
    action: "read",
    possession: "any",
  })
  async moduls(
    @graphql.Args() args: ModulFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Modul[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Modul",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Modul, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Modul",
    action: "read",
    possession: "own",
  })
  async modul(
    @graphql.Args() args: ModulFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Modul | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Modul",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Modul)
  @nestAccessControl.UseRoles({
    resource: "Modul",
    action: "create",
    possession: "any",
  })
  async createModul(
    @graphql.Args() args: CreateModulArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Modul> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Modul",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Modul"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Modul)
  @nestAccessControl.UseRoles({
    resource: "Modul",
    action: "update",
    possession: "any",
  })
  async updateModul(
    @graphql.Args() args: UpdateModulArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Modul | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Modul",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Modul"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Modul)
  @nestAccessControl.UseRoles({
    resource: "Modul",
    action: "delete",
    possession: "any",
  })
  async deleteModul(
    @graphql.Args() args: DeleteModulArgs
  ): Promise<Modul | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
