/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateCategryArgs } from "./CreateCategryArgs";
import { UpdateCategryArgs } from "./UpdateCategryArgs";
import { DeleteCategryArgs } from "./DeleteCategryArgs";
import { CategryFindManyArgs } from "./CategryFindManyArgs";
import { CategryFindUniqueArgs } from "./CategryFindUniqueArgs";
import { Categry } from "./Categry";
import { CategryService } from "../categry.service";

@graphql.Resolver(() => Categry)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CategryResolverBase {
  constructor(
    protected readonly service: CategryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Categry",
    action: "read",
    possession: "any",
  })
  async _categriesMeta(
    @graphql.Args() args: CategryFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Categry])
  @nestAccessControl.UseRoles({
    resource: "Categry",
    action: "read",
    possession: "any",
  })
  async categries(
    @graphql.Args() args: CategryFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Categry[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Categry",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Categry, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Categry",
    action: "read",
    possession: "own",
  })
  async categry(
    @graphql.Args() args: CategryFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Categry | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Categry",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Categry)
  @nestAccessControl.UseRoles({
    resource: "Categry",
    action: "create",
    possession: "any",
  })
  async createCategry(
    @graphql.Args() args: CreateCategryArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Categry> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Categry",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Categry"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Categry)
  @nestAccessControl.UseRoles({
    resource: "Categry",
    action: "update",
    possession: "any",
  })
  async updateCategry(
    @graphql.Args() args: UpdateCategryArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Categry | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Categry",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Categry"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Categry)
  @nestAccessControl.UseRoles({
    resource: "Categry",
    action: "delete",
    possession: "any",
  })
  async deleteCategry(
    @graphql.Args() args: DeleteCategryArgs
  ): Promise<Categry | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
